### ISSUE TITLE
Update Starter Samples with Full Backend Auth

### ISSUE THREAD

**Issue by ReservedDeveloper** [Microsoft/azure-spring-boot#244]
It'd be great to see an example project that handles the entire OAuth2 lifecycle entirely on the backend. The current starter sample for the `azure-active-directory-spring-boot-starter` handles the authentication via an AngularJS app. The documentation on [the Microsoft website](https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory) does not currently function as described due to a redirect uri error.

Having a full backend sample project would be a great way to verify expected behavior, as well as provide any updates as the starter package changes.

**Comment by yungez** [comment]
ping..

**Comment by ReservedDeveloper** [comment]
Sorry @yungez I got busy with another project. I'll need to recreate that really quick to record the full error.

**Comment by ReservedDeveloper** [comment]
The first part of the error is:

```
org.springframework.security.oauth2.client.resource.UserRedirectRequiredException: A redirect is required to get the users approval
	at org.springframework.security.oauth2.client.token.grant.code.AuthorizationCodeAccessTokenProvider.getRedirectForAuthorization(AuthorizationCodeAccessTokenProvider.java:359) ~[spring-security-oauth2-2.0.14.RELEASE.jar:na]
	at org.springframework.security.oauth2.client.token.grant.code.AuthorizationCodeAccessTokenProvider.obtainAccessToken(AuthorizationCodeAccessTokenProvider.java:205) ~[spring-security-oauth2-2.0.14.RELEASE.jar:na]
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.acquireAccessToken(OAuth2RestTemplate.java:221) ~[spring-security-oauth2-2.0.14.RELEASE.jar:na]
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.getAccessToken(OAuth2RestTemplate.java:173) ~[spring-security-oauth2-2.0.14.RELEASE.jar:na]
[...]
```

This happens following both the documentation linked in the OP, as well as the suggested properties changes suggested by user Lomid in the comments of the documentation.

**Comment by ccit-spence** [comment]
I have the same problem on how to get this working on a regular Spring MVC application not using a JS client library just regular Thymeleaf views

**Comment by machadolucas** [comment]
@ccit-spence I had the same problem and I managed to make it work by using Spring Boot OAuth2.
I basically followed these instructions, customizing them to Azure endpoints: http://www.baeldung.com/spring-security-openid-connect

You can also get more information here: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-scenarios#web-application-to-web-api

**Comment by JeSuisAlrick** [comment]
Just to add my two-cents to what @machadolucas said, you need to look specifically at these instructions: [Azure Active Directory v2.0 and the OpenID Connect protocol](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-oidc)

Basically, you can get your OpenID configs from by going to the following URL: 

```
https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration
```
Where `{tenant}` is the GUID of the active directory that you setup the keys in.

Plug the values from the resulting JSON response into the settings mentioned in @eugenp's tutorial [Spring Security and OpenID Connect](http://www.baeldung.com/spring-security-openid-connect)

P.S. @machadolucas, I wanted to tell you off because you didn't give a full explanation, but at least you pointed me in the right direction.

@microsoftopensource, if you're going to do open source, please dedicate the time and resources to keep your sample code in sync with the target solution. Popular open source projects move fast and you need to keep up!

**Comment by rsjorslev** [comment]
I played around some more with getting this to work "out of the box" with spring security 5 and its oauth2 / OpenID connect support and actually have it working now - but...
For some reason the v2.0 endpoints when used with authorisation code grant does not return token_type and access_token in it's response but rather just the id_token for verification purposes.
Using the urls from this openid-configiuration endpoint: (note v2.0 is removed)

`https://login.microsoftonline.com/{tenant}/.well-known/openid-configuration`

makes the response as per OpenID spec and it also implements an userinfo endpoints which does not seem available with v2.0.

This makes it super easy to implement following [this sample repo](https://github.com/jgrandja/springone2017-demo) as you can essentially just use this in the `application.yml` of the spring boot app:

```
spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: 11111111-1111-1111-1111-111111111111
            client-secret: superSecret123
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: Azure
        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/{tenant}/oauth2/authorize
            token-uri: https://login.microsoftonline.com/{tenant}/oauth2/token
            user-info-uri: https://login.microsoftonline.com/{tenant}/openid/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://login.microsoftonline.com/{tenant}/discovery/keys
```

you can try it out over at [openidconnect](https://openidconnect.net) and see the difference between using v2.0 and the non-v2.0 endpoints. Not sure why this is and why the v2.0 seems to not implement as per spec - haven't looked into the limitations of the v2.0 so I can't say.
