### ISSUE TITLE
Issue accessing graph API with access token acquired after successful login

### ISSUE THREAD

**Issue by jaimodha** [microsoft/azure-spring-boot#659]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter

- OS Type: MacOS
- Java version: 
  
  - 1.8
  

## Summary

The access token generated after successful login cannot be used to make graph api call (https://graph.microsoft.com) since the access token generated can only be used with the old AD graph API (https://graph.windows.net).  Tried to override the service endpoint to point to new graph API but that also requires to update the oauth endpoint to v2.0 endpoints but the library still fails, since the AzureADGraphClient has hard coded header to point to version 1.6.

## Reproduce steps

Attaching the configuration in comment that can reproduce the issue.

## Expected Results

There should be way to make it work with the new graph api to take advantage of the java graph sdk.

## Actual Results

Fails with we update the service endpoint to use new graph apis (https://graph.microsoft.com)

**Comment by jaimodha** [comment]
`azure:
  activedirectory:
    tenant-id: <teanant_id>
    active-directory-groups:  <group>
  service:
    endpoints:
      global:
        aadGraphApiUri: https://graph.microsoft.com/
        aadMembershipRestUri: https://graph.microsoft.com/v1.0/me/memberOf
spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: <client_id>
            client-secret: <client_secret>
            client-name: Azure
            provider: azure-oauth-provider
            scope: openid, https://graph.microsoft.com/user.read
            client-authentication-method: post
            authorization-grant-type: authorization_code
            userNameAttribute: name

        provider:
          azure-oauth-provider.token-uri: "https://login.microsoftonline.com/<teant_id>/oauth2/v2.0/token"
          azure-oauth-provider.authorization-uri: "https://login.microsoftonline.com/<teant_id>/oauth2/v2.0/authorize"
          azure-oauth-provider.user-info-uri: "https://graph.microsoft.com/oidc/userinfo"
          azure-oauth-provider.jwk-set-uri: "https://login.microsoftonline.com/<teant_id>/discovery/v2.0/keys"
          azure-oauth-provider.user-name-attribute: "name"`

**Comment by jaimodha** [comment]
azure:
  activedirectory:
    tenant-id: <teanant_id>
    active-directory-groups:  <group>
  service:
    endpoints:
      global:
        aadGraphApiUri: https://graph.microsoft.com/
        aadMembershipRestUri: https://graph.microsoft.com/v1.0/me/memberOf
spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: <client_id>
            client-secret: <client_secret>
            client-name: Azure
            provider: azure-oauth-provider
            scope: openid, https://graph.microsoft.com/user.read
            client-authentication-method: post
            authorization-grant-type: authorization_code
            userNameAttribute: name

        provider:
          azure-oauth-provider.token-uri: "https://login.microsoftonline.com/<teant_id>/oauth2/v2.0/token"
          azure-oauth-provider.authorization-uri: "https://login.microsoftonline.com/<teant_id>/oauth2/v2.0/authorize"
          azure-oauth-provider.user-info-uri: "https://graph.microsoft.com/oidc/userinfo"
          azure-oauth-provider.jwk-set-uri: "https://login.microsoftonline.com/<teant_id>/discovery/v2.0/keys"
          azure-oauth-provider.user-name-attribute: "name"

**Comment by jaimodha** [comment]
```
azure:
  activedirectory:
    tenant-id: <teanant_id>
    active-directory-groups:  <group>
  service:
    endpoints:
      global:
        aadGraphApiUri: https://graph.microsoft.com/
        aadMembershipRestUri: https://graph.microsoft.com/v1.0/me/memberOf
spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: <client_id>
            client-secret: <client_secret>
            client-name: Azure
            provider: azure-oauth-provider
            scope: openid, https://graph.microsoft.com/user.read
            client-authentication-method: post
            authorization-grant-type: authorization_code
            userNameAttribute: name

        provider:
          azure-oauth-provider.token-uri: "https://login.microsoftonline.com/<teant_id>/oauth2/v2.0/token"
          azure-oauth-provider.authorization-uri: "https://login.microsoftonline.com/<teant_id>/oauth2/v2.0/authorize"
          azure-oauth-provider.user-info-uri: "https://graph.microsoft.com/oidc/userinfo"
          azure-oauth-provider.jwk-set-uri: "https://login.microsoftonline.com/<teant_id>/discovery/v2.0/keys"
          azure-oauth-provider.user-name-attribute: "name"
```
