### ISSUE TITLE
Custom JWKSet Url property is ignored

### ISSUE THREAD

**Issue by sidyes** [microsoft/azure-spring-boot#818]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  
  - 1.8

  

## Summary

I want to use the AAD spring boot starter to secure REST calls by validating the provided Bearer Token. I needed to adapt the jwk set uri. Thusi, I added the following to my application.yaml:
```
security:
    oauth2:
      client:
        provider:
          azure-oauth-provider:
            jwk-set-uri: https://login.microsoftonline.com/<tenant-id>/discovery/v2.0/keys
```
Unfortunately, I am always getting the following error when sending requests to the server with a authorization header:
`Couldn't retrieve remote JWK set: connect timed out`

I debugged the application and realized that the wrong URL is taken there:
In the `RemoteJWKSet` class from nimbusds jwkSetURL is set to:   
`https://login.microsoftonline.com/common/discovery/keys/`
It seems that my configuration is just ignored here. Do you have a tip for me?

## Reproduce steps

Use the azure-active-directory-spring-boot-starter (v. 2.2.2) and try to change the jwk set uri property.

## Expected Results

It should use the correct URI.

## Actual Results

it uses the default common configuration.
