### ISSUE TITLE
Need to add query parameter to b2c

### ISSUE THREAD

**Issue by GarstMan78** [microsoft/azure-spring-boot#960]
we have a custom ui that uses a &application query parameter  how can i extend the sample project to make the yml support this
```yaml
spring:
  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
          #base-uri: ***
          base-uri: ***
          credential:
            client-id: ***
            client-secret: "***"
          login-flow: sign-up-or-sign-in
          query-parameters:
            application: "/CustomUI"
          logout-success-url: https://asu-nonprod.cat.com/
          user-flows:
            sign-up-or-sign-in: b2c_1a_p2_v1_signin_dev
            profile-edit: b2c_1a_p2_v1_profileedit_dev
            password-reset: <your-password-reset-user-flow-name>
          user-name-attribute-name: ***
```
