### ISSUE TITLE
Basic Tier ServiceBus Namespace in JMS 1.0 'not supported'

### ISSUE THREAD

**Issue by Seifeldin-Sabry** [microsoft/azure-spring-boot#965]
In [JMS Spring Documentation](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus?tabs=use-a-service-bus-queue,passwordless), It is mentioned that pricing-tier configuration accepts 'basic, standard, or premium'. 

Why do I get errors because I'm using a Basic tier namespace then?

```
The JMS message listener invoker setup failed for destination <destination>- trying to recover. Cause: Transaction is unsupported because the namespace <namespace> is of 'Basic' tier. [condition = amqp:not-allowed]
```

I followed everything step by step in the setup are there additional dependencies that I must add?

Also, it is mentioned that depending on the tier, different JMS versions are invoked. so what seems to be the issue here? I need JMS to setup multiple listeners as I have different queues.

in the main class I use these annotation:
```java
@EnableJms
@EnableIntegration
@SpringBootApplication
```

and this is what I have configured:
```yml
 spring:
    jms:
      servicebus:
        namespace: ${AZURE_SERVICEBUS_NAMESPACE}
        pricing-tier: ${AZURE_SERVICEBUS_PRICING_TIER}
        passwordless-enabled: true
        recieve-timeout: 10000
```

And how I register a listener:
`@JmsListener (destination = QUEUE_NAME, containerFactory = "jmsListenerContainerFactory")`

This is for listening to messages sent from an Azure function
